#!/bin/bash

CD_BASEURL="http://clouddocs.f5.com/training/community"

# Run a command.  Print error and exit if exitcode > 0
function run {
    "$@"
    local status=$?
    if [ $status -ne 0 ]; then
        echo "error with $1" >&2
        exit $status
    fi
    return $status
}

# Build lab submodules.  Set MAKE_OPT to pass addtional options/targets to make
function buildlabs {

	if [[ ! -z "$SKIP_BUILDLABS" ]]; then
		return
	fi

	if [[ -z "$BUILD_LIST" ]]; then
		BUILD_LIST=`ls labs`
	fi

	STATS_OPTIONS="-i"

	if [[ ! -z "$BUILD_ALL" ]]; then
		STATS_OPTIONS=""
	fi

	echo "BUILD_LIST=$BUILD_LIST"

	run mkdir -p hash

	for l in ${BUILD_LIST}
	do
 		REPOROOT=$PWD
 		LABREPOROOT="$PWD/labs/$l"
 		DOCROOT="$LABREPOROOT/docs"

 		RESPONSE=`curl --write-out %{http_code} -s -o $REPOROOT/hash/$l "$CD_BASEURL/$l/buildhash"`
 		CUR_HASH=`cd $LABREPOROOT && git rev-parse HEAD`
 		LIVE_HASH=`cat $REPOROOT/hash/$l`
 		if [[ "$RESPONSE" == "200" && "$CUR_HASH" == "$LIVE_HASH" ]]; then
 			if [[ -z "$BUILD_ALL" ]]; then
 				continue
 			fi
 		fi

 		run mkdir -p "_build/community/$l/html"
 		run mkdir -p "_build/community/$l/pdf"
 		cp common/preamble.tex $DOCROOT/
 		cp common/front_cover.png $DOCROOT/_static/
 		cp common/back_cover.png $DOCROOT/_static/
 		cp common/header.html $DOCROOT/_templates/
 		run script/containthedocs make -C "$DOCROOT" $MAKE_OPT html latexpdf
 		run cd $LABREPOROOT
 		run ./containthedocs-pdf-perclass.sh
 		run git rev-parse HEAD >> "$REPOROOT/_build/community/$l/buildhash"
 		run cd $REPOROOT
 		run cp -Rf "$DOCROOT"/_build/html/* "_build/community/$l/html"
 		run cp -Rf "$DOCROOT"/_build/latex/*.pdf "_build/community/$l/pdf"
 		run cp -Rf "$LABREPOROOT"/pdf/*.pdf "_build/community/$l/pdf"
	done
}

# Build the root lab index
function buildroot {
	run mkdir -p _build/community/
	run cp -Rf landing/* _build/community/
}

function buildstats {
	if [[ ! -z "$SKIP_BUILDLABS" ]]; then
		return
	fi

	run script/containthedocs python3 script/stats.py ${STATS_OPTIONS} `pwd`/_build `pwd`/_build/community/js/stats.json
}

# Clean up the _build directory
function cleanbuild {
	run rm -Rf $PWD/_build/
	run mkdir -p _build
}